Class {
	#name : 'DevScale',
	#superclass : 'Object',
	#category : 'Canvasinator',
	#package : 'Canvasinator'
}

{ #category : 'as yet unclassified' }
DevScale class >> advanced [
	^ Advanced
]

{ #category : 'accessing' }
DevScale class >> beginning [
	^ Beginning
]

{ #category : 'as yet unclassified' }
DevScale class >> orienting [
	^ Orienting
]

{ #category : 'accessing' }
DevScale class >> proficient [
	^ Proficient
]

{ #category : 'as yet unclassified' }
DevScale class >> undefined [
	^ Undefined
]
